[game]
desc               = "UPDATE ME"
lobbyenabled       = true
lobbyduration      = 180

# New players can't join a server without admins
[game.panic_bunker]
enabled = true
min_overall_minutes = 600 # Should be lower, 240?
disable_with_admins = true
enable_without_admins = true
show_reason = true
custom_reason = "UPDATE ME"

[infolinks]
discord    = "UPDATE ME"
github     = "https://github.com/new-frontiers-14/frontier-station-14"
website    = "UPDATE ME"
wiki       = "UPDATE ME"
patreon    = "UPDATE ME"
bug_report = "https://github.com/new-frontiers-14/frontier-station-14/issues"
appeal     = "UPDATE ME - DISCORD"

[net]
max_connections = 1024
tickrate = 30

[vote]
restart_required_ratio = 0.85
preset_enabled = false

[netres]
limit    = 10.0

[admin]
see_own_notes   = true
deadmin_on_join = true
allow_multi_server_play = false
[admin.alert]
min_players_sharing_connection = 2

[server]
id         = "frontier"
rules_file = "FrontierRuleset"
uptime_restart_minutes = 0

[discord]
rich_main_icon_id = "frontier"

# general mrp stuff
[ic]
flavor_text = true
punctuation = true

[worldgen]
enabled = true

[rules]
time = 60

[ahelp]
admin_prefix = false
admin_prefix_webhook = false

[votekick]
enabled = false
eligible_number = 5
initiator_ghost_requirement = false
voter_ghost_requirement = false

[atmos]
space_wind = true

[shuttle]
arrivals = false
emergency_dock_time = 360 # an extra 2 minutes over the default
emergency_transit_time_min = 300
auto_call_extension_time = 45
emergency_early_launch_allowed = true # MRP server command ban time

[biomass]
easy_mode = false # reclaimer can work on soul-ful bodies, mrp server

[control]
storage_limit = 3